
name: "Terraform1"

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Azure Infra
        env: 
            ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
            ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
            ARM_TENANT_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
            ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_TEANANT_ID}}
    
        run: |
          cd ${{ github.workspace }}/terraformsnipeit
          terraform init
          terraform plan
          terraform apply -auto-approve
